### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by eead-csic-compbio** [montecuollo/EFMC#1]
Hi,
can you please explain howto to compile the compressor and how to include it as a library in other programs?
 Many thanks, Bruno

**Comment by kounkou** [comment]
Hi @montecuollo

I just wanted to answer @eead-csic-compbio here,
Instructions are in the release note.
https://github.com/montecuollo/E2FM/releases
Maybe you should put it in the readme.md, I can send you a PR if you want me to. :smile:

Best

**Comment by montecuollo** [comment]
Instructions are in the release note: 

https://github.com/montecuollo/E2FM/releases

Thank you.
